import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { text, readability, purpose, bypassLevel } = await req.json();

    if (!text || typeof text !== "string") {
      return new Response(
        JSON.stringify({ error: "Text is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const OPENROUTER_API_KEY = Deno.env.get("OPENROUTER_API_KEY");
    if (!OPENROUTER_API_KEY) {
      throw new Error("OPENROUTER_API_KEY is not configured");
    }

    const readabilityGuide = {
      "general": "Use everyday vocabulary, moderate sentence length (12-18 words avg), clear structures.",
      "university": "Use sophisticated vocabulary, varied sentence length (15-25 words avg), complex ideas expressed clearly.",
      "doctorate": "Use precise academic vocabulary, formal but not robotic tone, proper citations style if present."
    };

    const purposeGuide = {
      "academic": "Maintain scholarly tone, use hedging language ('suggests', 'appears to'), include topic sentences, logical flow.",
      "marketing": "Persuasive, benefit-focused, use power words, create urgency, clear calls to action.",
      "business": "Professional but warm, action-oriented, clear and concise, avoid buzzwords.",
      "journalism": "Inverted pyramid style, lead with key facts, objective tone, attributed sources, newsworthy angle.",
      "email": "Concise and direct, clear subject relevance, professional greeting/closing, actionable next steps.",
      "essay": "Develop a clear thesis, support with evidence, logical paragraph transitions, reflective conclusion.",
      "story": "Engaging narrative arc, vivid descriptions, character development, dialogue where appropriate, emotional resonance."
    };

    const bypassGuide = {
      "simple": "Light touch - fix obvious AI patterns while preserving structure.",
      "standard": "Moderate rewrite - restructure sentences, add human touches, vary vocabulary.",
      "enhanced": "Deep rewrite - completely reimagine sentence structures, add personality, use idioms, include natural imperfections."
    };

    const systemPrompt = `You are a master ghostwriter who transforms AI-generated text into genuinely human-sounding content. Your rewrites must be UNDETECTABLE by AI detection tools like GPTZero, Turnitin, and Originality.ai.

## YOUR MISSION
Transform the input into text that reads like it was written by a thoughtful human, not generated by AI.

## DETECTION PATTERNS TO ELIMINATE
AI detectors look for these - you MUST avoid them:
- Uniform sentence length and rhythm (AI writes with mechanical consistency)
- Overuse of transitional phrases ("Furthermore", "Moreover", "Additionally", "In conclusion")
- Perfect parallel structures and balanced clauses
- Excessive hedging ("It is important to note that", "It should be mentioned")
- Generic examples and platitudes
- Starting sentences with "This", "It", "There" repeatedly
- Overly formal or stilted phrasing
- Lists that are too clean and organized
- Lack of contractions in casual contexts
- Missing personal voice or opinion

## HUMANIZATION TECHNIQUES TO APPLY
1. **Sentence Variety**: Mix very short punchy sentences with longer flowing ones. Start sentences differently - with subjects, prepositional phrases, dependent clauses, even single words.

2. **Natural Imperfections**: Add parenthetical asides (like this one), dashes for emphasis—when it feels right, and occasional sentence fragments. For effect.

3. **Authentic Voice**: Include personal observations, mild opinions, rhetorical questions. What would a real person add here?

4. **Concrete Details**: Replace generic statements with specific examples. Instead of "many people," say "my colleague Sarah" or "three out of five students in my study group."

5. **Colloquial Language**: Use contractions (don't, won't, it's), informal transitions (anyway, so, honestly, look), and natural filler where appropriate.

6. **Imperfect Organization**: Real writing isn't perfectly structured. Let ideas flow naturally, circle back, digress slightly.

7. **Active Engagement**: Address the reader occasionally, ask questions, acknowledge counterpoints informally.

## CONTEXT-SPECIFIC SETTINGS
- Readability: ${readability || "general"} - ${readabilityGuide[readability as keyof typeof readabilityGuide] || readabilityGuide.general}
- Purpose: ${purpose || "academic"} - ${purposeGuide[purpose as keyof typeof purposeGuide] || purposeGuide.academic}
- Intensity: ${bypassLevel || "standard"} - ${bypassGuide[bypassLevel as keyof typeof bypassGuide] || bypassGuide.standard}

## CRITICAL RULES
1. PRESERVE all factual information, data, and core meaning
2. NEVER add disclaimers, notes, or meta-commentary
3. NEVER mention that you're rewriting or humanizing
4. Output ONLY the rewritten text - nothing else
5. Match the approximate length of the original (within 10-15%)
6. If the original has formatting (headers, bullets), preserve the structure but humanize the content

Now rewrite the following text to be genuinely human:`;

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://writehuman.app",
        "X-Title": "WriteHuman",
      },
      body: JSON.stringify({
        model: "anthropic/claude-3-haiku",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Please humanize the following text:\n\n${text}` },
        ],
        stream: true,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI credits exhausted. Please add credits to continue." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errorText = await response.text();
      console.error("OpenRouter error:", response.status, errorText);
      return new Response(
        JSON.stringify({ error: "AI service error. Please try again." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(response.body, {
      headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
    });
  } catch (error) {
    console.error("Humanize error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
